### ISSUE TITLE
A suggestion for the configmap data structure

### ISSUE THREAD

**Issue by tpiperatgod** [liangyuanpeng/karmada-extend#7]
Can we make the following changes to the configuration data:

```yaml
data:
    <cluster A name>:
        type: local
        replicas: 2
    <cluster B name>:
        type: remote
        replicas: 1
    <cluster C name>:
        type: remote
        replicas: 3
```

So that the local operator can efficiently find its cluster name.

Also, in most cases the sts workload will recommend the order in which the replicas should be started, so can we set the order number in the data? (optional)

like this:

```yaml
data:
    <cluster A name>:
        type: local
        replicas: 2
        order: 1
    <cluster B name>:
        type: remote
        replicas: 1
        order: 2
    <cluster C name>:
        type: remote
        replicas: 3
        order: 3
```
